services:
    # Migration checker
    app:
        build:
            context: ./docker
            target: php-base
        restart: always
        environment:
            # XDEBUG_MODE: "debug,develop"
            XDEBUG_MODE: "${XDEBUG_MODE:-off}"
            PHP_IDE_CONFIG: "${PHP_IDE_CONFIG:-serverName=migration-checker}"
        volumes:
            - .:/app
            - /var/run/docker.sock:/var/run/docker.sock
