on:
  pull_request:
    paths-ignore: &paths_ignore
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - Makefile
      - 'phpunit.xml.dist'

  push:
    paths-ignore: *paths_ignore

name: Code analysis

jobs:
  syntax:
    name: Syntax | PHP ${{ matrix.php }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.5
          - 8.4
          - 8.3
          - 8.2
          - 8.1

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up the project
        uses: ./.github/actions/setup-project
        with:
          php: ${{ matrix.php }}

      - name: PHP syntax validation
        run: |
          vendor/bin/parallel-lint \
            --colors \
            src tests

  coding-style:
    name: Coding style
    needs: syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up the project
        uses: ./.github/actions/setup-project
        with:
          php: 8.5

      - name: Coding style analysis
        run: |
          vendor/bin/phpcs \
            --extensions=php \
            --colors \
            --standard=PSR12Ext \
            --runtime-set php_version 80100 \
            --ignore=vendor/* \
            -p \
            -s \
            .


  phpstan:
    name: PHPStan
    needs: syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up the project
        uses: ./.github/actions/setup-project
        with:
          php: 8.1

      - name: Static analysis with PHPStan
        run: |
          vendor/bin/codecept build
          vendor/bin/phpstan analyse \
            --memory-limit=256M \
            .

  rector:
    name: Rector
    needs: syntax
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up the project
        uses: ./.github/actions/setup-project
        with:
          php: 8.1

      - name: Code analysis with Rector
        run: |
          vendor/bin/rector --dry-run
