on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: DB integration tests

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      shard-count: 3
    outputs:
      shards: ${{ steps.set-shards.outputs.shards }}
      shard-count: ${{ steps.set-shard-count.outputs.shard-count }}
    steps:
      - id: set-shards
        # Generates a JSON array [1, 2, 3, ...]
        run: echo "shards=$(seq 1 ${{ env.shard-count }} | jq -R . | jq -s -c .)" >> $GITHUB_OUTPUT
      - id: set-shard-count
        run: echo "shard-count=${{ env.shard-count }}" >> $GITHUB_OUTPUT

  tests:
    name: PHP ${{ matrix.php }} Shard ${{ matrix.shard }}
    needs: setup
    runs-on: ubuntu-latest
    env:
      shard-count: ${{ needs.setup.outputs.shard-count }}

    strategy:
      matrix:
        php:
          - 8.1
        shard: ${{ fromJson(needs.setup.outputs.shards) }}

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@v6

      - name: Store Docker builder cache
        uses: docker/build-push-action@v6
        with:
          context: ./docker
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: false
          tags: checker:latest
          target: php-base
          load: true
          # cache between workflow runs:
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Install dependencies with Composer
        run: docker run --rm -v ".:/app" checker composer install

      - name: Run DB integration tests with Codeception
        run: |
          docker run --rm \
            -v ".:/app" \
            -v "/var/run/docker.sock:/var/run/docker.sock" \
            --add-host=host.docker.internal:host-gateway \
            checker \
            codecept run Db \
            --debug \
            --shard "${{ matrix.shard }}/${{ env.shard-count }}"
